version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: someone_talking_postgres
    restart: always
    environment:
      POSTGRES_DB: someone_talking
      POSTGRES_USER: someone_talking_user
      POSTGRES_PASSWORD: someone_talking_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
